### ISSUE TITLE
Paleta de colores 1: Página de carga con logo de la app

### ISSUE THREAD

**Issue by Oliasaew** [Centinela-RR/mockups#4]
Entrega de 4 propuestas con la paleta de colores asignada previamente, considerando el contraste de colores entre logo de la app y fondo

**Comment by 2021030063** [comment]
**Mañana presentan su trabajo!!**
Tiempo casi se acaba, hurry up fellas.

**Comment by Yoel1515** [comment]
Listo pero donde lo subo

**Comment by 2021030063** [comment]
Nueva carpeta en la repo "propuestas" para tener un historial
